# Dependabot will run on day 3 of each month at 01:42 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "42 1 3 * *"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"
  - package-ecosystem: "github-actions"
    directories: "**/*"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "42 1 3 * *"
    open-pull-requests-limit: 15
